In [1]:
import torch

In [2]:
# 1D Matrix
one_d = torch.arange(0,9)
one_d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
# 2D Matrix

two_d = one_d.view(3,3)
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [4]:
# Check Dimensions
two_d.dim()

2

In [5]:
# Slicing
two_d[0,0] # Get the first value

tensor(0)

In [6]:
two_d[1,2]# Get the 5 value

tensor(5)

In [7]:
x = torch.arange(18).view(2,3,3) # 3D
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [8]:
x3 = torch.arange(18).view(3,2,3) # 3D 
x3

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [9]:
# Get the number 10 from the second group
x3[1,1,1]

tensor(10)

In [10]:
# Get first row of second block
x3[1,0:2,1]

tensor([ 7, 10])

In [13]:
# Matrix Multiplication
# # Rows, # Columns
# M * N | N * M.  N and N must match

In [14]:
import torch

In [16]:
mat_a = torch.tensor([0,3,5,5,5,2]).view(2,3)
mat_a

tensor([[0, 3, 5],
        [5, 5, 2]])

In [18]:
mat_b = torch.tensor([3,4,3,-2,4,-2]).view(3,2)
mat_b

tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [20]:
# Now we can multiply the matrices
torch.matmul(mat_a,mat_b)

tensor([[ 29, -16],
        [ 38,   6]])

In [22]:
# Another way
mat_a @ mat_b

tensor([[ 29, -16],
        [ 38,   6]])

In [25]:
# Gradient and Derivatives

![](https://kcmunninstoragev2.blob.core.windows.net/public/pytorch_derivative.JPG)

Derivative of this function:

$9x^4+2x^3x^2+6x+1$

In [32]:
# Derivative of function at value x = 2 is 330, from manual calculation

In [31]:
x = torch.tensor(2.0, requires_grad = True) # Need this parameter
y = 9*x**4 + 2*x**3 + 3*x**2 + 6*x + 1
y.backward()
x.grad

tensor(330.)

Derivative of this function:

$y = x^2 + z^3$

![](https://kcmunninstoragev2.blob.core.windows.net/public/pytorch_derivative2.JPG)

In [36]:
x = torch.tensor(1.0, requires_grad=True)
z = torch.tensor(2.0, requires_grad=True)
y = x**2 + z**3
y.backward()
x.grad

tensor(2.)

In [37]:
z.grad

tensor(12.)