In [3]:
!pip3 install torch

You should consider upgrading via the 'pip install --upgrade pip' command.


In [1]:
import torch

In [6]:
# Creating a 1-D tensor
v = torch.tensor([1,2,3,4,5,6])
print(v)

tensor([1, 2, 3, 4, 5, 6])


In [7]:
# Viewing the data type
print(v.dtype)

torch.int64


In [8]:
# indexing
print(v[1])

tensor(2)


In [9]:
# Index slicing
print(v[1:])

tensor([2, 3, 4, 5, 6])


In [11]:
f = torch.FloatTensor([1,2,3,4,5,6])
print(f)

tensor([1., 2., 3., 4., 5., 6.])


In [12]:
# Size
print(f.size())

torch.Size([6])


In [14]:
# Type
# Size
print(f.dtype)

torch.float32


In [13]:
# Reshape to 6 rows in 1 column (Rows, Column)
v.view(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [16]:
# Reshape with neagtive, value inferred based on length of tensor
# E.g. length of vector is 6, it has 3 rows, therefore it must have two columns
v.view(3,-1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [19]:
import numpy as np

In [24]:
# Convert Numpy array to tensor
a = np.array([1,2,3,4,5])
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [23]:
# Convert Tensor back to Numpy
numpy_cnv = tensor_cnv.numpy
print(numpy_cnv)

<built-in method numpy of Tensor object at 0x7fa8ab4ffc60>
